{
 "title": "Proxmox VE Home",
 "description": "Home dashboard with alerting, nodes, syslog,VM/CT for cluster Proxmox VE",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Status Alarm", "type": "alertlist", "gridPos": { "h": 13, "w": 7, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       { "params": [ "uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "nodes" }
     ]
    }
   ]
  },
  { "title": "Dashboard Proxmox VE", "type": "dashlist", "gridPos": { "h": 13, "w": 4, "x": 16, "y": 0 } },
  { "title": "Dashboard", "type": "dashlist", "gridPos": { "h": 13, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT mean(\"memused\") / mean(\"memtotal\") *100 FROM \"memory\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/ 1073741824" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"perc\") AS Perc FROM \n(SELECT used / total *100  AS perc FROM \"system\" WHERE (\"object\" = 'storages' ) AND $timeFilter )\nGROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "storages" }
     ]
    }
   ]
  },
  {
   "title": "Syslog",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "measurement": "syslog",
     "query": "SELECT \"host\", \"appname\", \"facility\", \"severity\", \"message\", \"severity_code\" FROM \"syslog\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "appname" ], "type": "field" }
      ],
      [
       { "params": [ "facility" ], "type": "field" }
      ],
      [
       { "params": [ "severity" ], "type": "field" }
      ],
      [
       { "params": [ "message" ], "type": "field" }
      ],
      [
       { "params": [ "severity_code" ], "type": "field" }
      ],
      [
       { "params": [ "host" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "err" },
      { "condition": "OR", "key": "severity", "operator": "=", "value": "warning" }
     ]
    }
   ]
  },
  {
   "title": "VM / CT",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "object" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ],
      [
       { "params": [ "cpu" ], "type": "field" }
      ],
      [
       { "params": [ "cpus" ], "type": "field" }
      ],
      [
       { "params": [ "mem" ], "type": "field" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" }
      ],
      [
       { "params": [ "disk" ], "type": "field" }
      ],
      [
       { "params": [ "maxdisk" ], "type": "field" }
      ],
      [
       { "params": [ "qmpstatus" ], "type": "field" }
      ],
      [
       { "params": [ "vmid" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" },
      { "condition": "OR", "key": "object", "operator": "=", "value": "lxc" }
     ]
    }
   ]
  }
 ]
}