{
 "title": "Proxmox VE Alert",
 "description": "Proxmox VE alert dashboard",
 "tags": [
  "Proxmox VE",
  "Alert"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Status Alert", "type": "alertlist", "gridPos": { "h": 12, "w": 9, "x": 0, "y": 0 } },
  {
   "title": "ZFS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_pool ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs_pool",
     "select": [
      [
       { "params": [ "nread" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Node Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_name ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "unit", "operator": "=", "value": "degrees_c" }
     ]
    }
   ]
  },
  {
   "title": "Node uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"perc\") as perc FROM \n(SELECT used / total * 100.0 as perc FROM \"system\" WHERE (\"object\" = 'storages') AND $timeFilter) GROUP BY time($__interval), \"host\",\"type\"",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "nodes" }
     ]
    }
   ]
  },
  {
   "title": "Storages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host ($tag_type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"perc\") as perc FROM \n(SELECT used / total * 100.0 as perc FROM \"system\" WHERE (\"object\" = 'storages') AND $timeFilter) GROUP BY time($__interval), \"host\",\"type\"",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "storages" }
     ]
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Nodes CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpustat",
     "query": "SELECT mean(\"cpu\") * 100 FROM \"cpustat\" WHERE $timeFilter GROUP BY time(1m), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 100" ], "type": "math" },
       { "params": [ "CPU usage" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nodes CPU I/O Wait",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "wait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" },
       { "params": [ "CPU I/O Wait" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nodes CPU Load Average (1 Min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpustat",
     "query": "SELECT mean(\"avg1\") AS \"CPU Load Average (1 Min)\" FROM \"cpustat\" WHERE $timeFilter GROUP BY time(1m), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "avg1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPU Load Average (1 Min)" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nodes Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT mean(\"memused\")/mean(\"memtotal\") * 100 AS \"Memory Usage\" FROM \"memory\" WHERE $timeFilter GROUP BY time($__interval) ,host fill(null)",
     "select": [
      [
       { "params": [ "memused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "KVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "VM/CT CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host ($tag_vmid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "vmid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"cpu\")  * 100 FROM \"system\" WHERE (\"object\" = 'qemu' AND \"host\" =~ /^$virtual_machine$/ AND \"nodename\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" },
       { "params": [ "VM CPU" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "qemu" },
      { "condition": "OR", "key": "object", "operator": "=", "value": "lxc" }
     ]
    }
   ]
  }
 ]
}